name = "Pumasv2"
uuid = "a5c24935-b330-4fef-a8bd-b84c1d42e82b"
authors = ["d"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
